name:         guppy_dart
version:      0.0.2
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Dart wrapper for the Guppy equation editor.
homepage:     https://github.com/eqdb/guppy-dart
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  browser:    ^0.10.0+2
  js:         ^0.6.1
